### ISSUE TITLE
Remove recipes that are covered by chef-cookbooks/homebrew

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-homebrew#18]
chef-cookbooks/homebrew does most of what this cookbook intends to do, and is more "canonical". If [this PR](https://github.com/chef-cookbooks/homebrew/pull/73) is accepted, then the only novel functionality our cookbook provides is the launchctl recipe.

We should consider deprecating or removing most of this cookbook, and maybe moving the launchctl recipe somewhere else.

@hiremaga Thoughts?

**Comment by hiremaga** [comment]
Sounds promising.

In the past they've been slow to review & merge pretty obvious PRs forcing us to use a fork temporarily. This makes me hesitate a little. Let's see how your recent round of PRs to the homebrew cookbook go and re-evaluate.

**Comment by wendorf** [comment]
The PR was merged yesterday.

**Comment by wendorf** [comment]
Removed everything except `sprout-homebrew::launchctl`.
