### ISSUE TITLE
Allow custom taps

### ISSUE THREAD

**Issue by chendrix** [pivotal-sprout/sprout-homebrew#19]
I really want to install `cloudfoundry-cli` via `sprout-homebrew` but it's under a custom tap `pivotal/homebrew-tap`.

Is there a way to specify custom taps? If not, there should be.

**Comment by wendorf** [comment]
Hi Chris,

We spoke a bit in person, but I wanted to respond here as well:

sprout-homebrew doesn't have a facility for adding custom taps, but it is baked into the official chef homebrew cookbook. As long as you have `cookbook 'homebrew'` in your Cheffile, you can run the `homebrew::install_taps` recipe which will look for the `node['homebrew']['taps']` array. You can see that being used in the [cloudfoundry/sprout-capi](https://github.com/cloudfoundry/sprout-capi/blob/7a7a740/soloistrc#L204-L208) sprout-wrap clone.

Hope that helps,
Dan

**Comment by wendorf** [comment]
Closing this issue due to age. If you have any additional questions or concerns, please feel free to open another issue.


Thanks,
Dan
