### ISSUE TITLE
Error: Tap caskroom/cask already tapped.

### ISSUE THREAD

**Issue by funcode** [pivotal-sprout/sprout-homebrew#21]
This is found on a fresh Mac OS Yosemite. When sprout-wrap('bundle exec soloist') failed due to some problems, and I fixed it and ran it again, I got the error below. I have to "brew untap caskroom/cask" every time to continue.

Recipe: sprout-homebrew::casks

  * sprout_homebrew_cask[chefdk] action install[2015-11-10T14:49:14+08:00] INFO: Processing sprout_homebrew_cask[chefdk] action install (sprout-homebrew::casks line 7)

  

Recipe: sprout-homebrew::cask

  * directory[/usr/local/Library/Taps] action create[2015-11-10T14:49:14+08:00] INFO: Processing directory[/usr/local/Library/Taps] action create (sprout-homebrew::cask line 3)

 (up to date)

  * execute[tap cask] action run[2015-11-10T14:49:14+08:00] INFO: Processing execute[tap cask] action run (sprout-homebrew::cask line 8)

Error: Tap caskroom/cask already tapped.

**Comment by wendorf** [comment]
Hi @funcode ,

The `sprout-homebrew::casks` and `sprout-homebrew::cask` recipes have been removed in favor of [`homebrew::install_casks`](https://github.com/chef-cookbooks/homebrew/blob/master/recipes/install_casks.rb). If you migrate to that cookbook, you should see better behavior (see the sprout-homebrew [README](https://github.com/pivotal-sprout/sprout-homebrew/blob/master/README.md) for migration instructions).
