### ISSUE TITLE
/opt is not readable by "other" after first run.

### ISSUE THREAD

**Issue by hjhart** [pivotal-sprout/sprout-homebrew#8]
After fresh install:

``` |2.1.0| wanelos-iMac-2 in /
○ → cd /opt
-bash: cd: /opt: Permission denied
```

My current fix:
```bash
sudo chmod -R o+rx /opt
```

Then everything is groovy.
```
 |2.1.0| wanelos-iMac-2 in /
○ → cd opt

 |2.1.0| wanelos-iMac-2 in /opt
○ → ls -la
```

Anyone else having this problem?

**Comment by wendorf** [comment]
Hi @hjhart,

Most of the sprout-homebrew favor of the [homebrew](https://github.com/chef-cookbooks/homebrew) cookbook. If you migrate to that cookbook, you should see better behavior (see the sprout-homebrew [README](https://github.com/pivotal-sprout/sprout-homebrew/blob/master/README.md) for migration instructions).

Thanks,
@wendorf
